// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_head.proto

#ifndef PROTOBUF_packet_5fhead_2eproto__INCLUDED
#define PROTOBUF_packet_5fhead_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace proto {
class DebugNotify;
class DebugNotifyDefaultTypeInternal;
extern DebugNotifyDefaultTypeInternal _DebugNotify_default_instance_;
class PacketHead;
class PacketHeadDefaultTypeInternal;
extern PacketHeadDefaultTypeInternal _PacketHead_default_instance_;
class PacketHead_ExtMapEntry;
class PacketHead_ExtMapEntryDefaultTypeInternal;
extern PacketHead_ExtMapEntryDefaultTypeInternal _PacketHead_ExtMapEntry_default_instance_;
class PacketHead_ServiceAppIdMapEntry;
class PacketHead_ServiceAppIdMapEntryDefaultTypeInternal;
extern PacketHead_ServiceAppIdMapEntryDefaultTypeInternal _PacketHead_ServiceAppIdMapEntry_default_instance_;
}  // namespace proto

namespace proto {

namespace protobuf_packet_5fhead_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_packet_5fhead_2eproto

enum DebugNotify_Enum {
  DebugNotify_Enum_ZERO = 0,
  DebugNotify_Enum_CMD_ID = 101,
  DebugNotify_Enum_TARGET_SERVICE = 101,
  DebugNotify_Enum_ENET_CHANNEL_ID = 2,
  DebugNotify_Enum_ENET_IS_RELIABLE = 1,
  DebugNotify_Enum_DebugNotify_Enum_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DebugNotify_Enum_DebugNotify_Enum_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DebugNotify_Enum_IsValid(int value);
const DebugNotify_Enum DebugNotify_Enum_Enum_MIN = DebugNotify_Enum_ZERO;
const DebugNotify_Enum DebugNotify_Enum_Enum_MAX = DebugNotify_Enum_CMD_ID;
const int DebugNotify_Enum_Enum_ARRAYSIZE = DebugNotify_Enum_Enum_MAX + 1;

const ::google::protobuf::EnumDescriptor* DebugNotify_Enum_descriptor();
inline const ::std::string& DebugNotify_Enum_Name(DebugNotify_Enum value) {
  return ::google::protobuf::internal::NameOfEnum(
    DebugNotify_Enum_descriptor(), value);
}
inline bool DebugNotify_Enum_Parse(
    const ::std::string& name, DebugNotify_Enum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DebugNotify_Enum>(
    DebugNotify_Enum_descriptor(), name, value);
}
enum DebugNotify_Retcode {
  DebugNotify_Retcode_SUCC = 0,
  DebugNotify_Retcode_FAIL = 1,
  DebugNotify_Retcode_DebugNotify_Retcode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DebugNotify_Retcode_DebugNotify_Retcode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DebugNotify_Retcode_IsValid(int value);
const DebugNotify_Retcode DebugNotify_Retcode_Retcode_MIN = DebugNotify_Retcode_SUCC;
const DebugNotify_Retcode DebugNotify_Retcode_Retcode_MAX = DebugNotify_Retcode_FAIL;
const int DebugNotify_Retcode_Retcode_ARRAYSIZE = DebugNotify_Retcode_Retcode_MAX + 1;

const ::google::protobuf::EnumDescriptor* DebugNotify_Retcode_descriptor();
inline const ::std::string& DebugNotify_Retcode_Name(DebugNotify_Retcode value) {
  return ::google::protobuf::internal::NameOfEnum(
    DebugNotify_Retcode_descriptor(), value);
}
inline bool DebugNotify_Retcode_Parse(
    const ::std::string& name, DebugNotify_Retcode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DebugNotify_Retcode>(
    DebugNotify_Retcode_descriptor(), name, value);
}
// ===================================================================

class PacketHead_ExtMapEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.PacketHead.ExtMapEntry) */ {
 public:
  PacketHead_ExtMapEntry();
  virtual ~PacketHead_ExtMapEntry();

  PacketHead_ExtMapEntry(const PacketHead_ExtMapEntry& from);

  inline PacketHead_ExtMapEntry& operator=(const PacketHead_ExtMapEntry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PacketHead_ExtMapEntry(PacketHead_ExtMapEntry&& from) noexcept
    : PacketHead_ExtMapEntry() {
    *this = ::std::move(from);
  }

  inline PacketHead_ExtMapEntry& operator=(PacketHead_ExtMapEntry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PacketHead_ExtMapEntry& default_instance();

  static inline const PacketHead_ExtMapEntry* internal_default_instance() {
    return reinterpret_cast<const PacketHead_ExtMapEntry*>(
               &_PacketHead_ExtMapEntry_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PacketHead_ExtMapEntry* other);
  friend void swap(PacketHead_ExtMapEntry& a, PacketHead_ExtMapEntry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PacketHead_ExtMapEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  PacketHead_ExtMapEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PacketHead_ExtMapEntry& from);
  void MergeFrom(const PacketHead_ExtMapEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PacketHead_ExtMapEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::uint32 key() const;
  void set_key(::google::protobuf::uint32 value);

  // uint32 value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::uint32 value() const;
  void set_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.PacketHead.ExtMapEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 key_;
  ::google::protobuf::uint32 value_;
  mutable int _cached_size_;
  friend struct protobuf_packet_5fhead_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PacketHead_ServiceAppIdMapEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.PacketHead.ServiceAppIdMapEntry) */ {
 public:
  PacketHead_ServiceAppIdMapEntry();
  virtual ~PacketHead_ServiceAppIdMapEntry();

  PacketHead_ServiceAppIdMapEntry(const PacketHead_ServiceAppIdMapEntry& from);

  inline PacketHead_ServiceAppIdMapEntry& operator=(const PacketHead_ServiceAppIdMapEntry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PacketHead_ServiceAppIdMapEntry(PacketHead_ServiceAppIdMapEntry&& from) noexcept
    : PacketHead_ServiceAppIdMapEntry() {
    *this = ::std::move(from);
  }

  inline PacketHead_ServiceAppIdMapEntry& operator=(PacketHead_ServiceAppIdMapEntry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PacketHead_ServiceAppIdMapEntry& default_instance();

  static inline const PacketHead_ServiceAppIdMapEntry* internal_default_instance() {
    return reinterpret_cast<const PacketHead_ServiceAppIdMapEntry*>(
               &_PacketHead_ServiceAppIdMapEntry_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PacketHead_ServiceAppIdMapEntry* other);
  friend void swap(PacketHead_ServiceAppIdMapEntry& a, PacketHead_ServiceAppIdMapEntry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PacketHead_ServiceAppIdMapEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  PacketHead_ServiceAppIdMapEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PacketHead_ServiceAppIdMapEntry& from);
  void MergeFrom(const PacketHead_ServiceAppIdMapEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PacketHead_ServiceAppIdMapEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::uint32 key() const;
  void set_key(::google::protobuf::uint32 value);

  // uint32 value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::uint32 value() const;
  void set_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.PacketHead.ServiceAppIdMapEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 key_;
  ::google::protobuf::uint32 value_;
  mutable int _cached_size_;
  friend struct protobuf_packet_5fhead_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PacketHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.PacketHead) */ {
 public:
  PacketHead();
  virtual ~PacketHead();

  PacketHead(const PacketHead& from);

  inline PacketHead& operator=(const PacketHead& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PacketHead(PacketHead&& from) noexcept
    : PacketHead() {
    *this = ::std::move(from);
  }

  inline PacketHead& operator=(PacketHead&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PacketHead& default_instance();

  static inline const PacketHead* internal_default_instance() {
    return reinterpret_cast<const PacketHead*>(
               &_PacketHead_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PacketHead* other);
  friend void swap(PacketHead& a, PacketHead& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PacketHead* New() const PROTOBUF_FINAL { return New(NULL); }

  PacketHead* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PacketHead& from);
  void MergeFrom(const PacketHead& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PacketHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef PacketHead_ExtMapEntry ExtMapEntry;
  typedef PacketHead_ServiceAppIdMapEntry ServiceAppIdMapEntry;

  // accessors -------------------------------------------------------

  // repeated .proto.PacketHead.ExtMapEntry ext_map = 23;
  int ext_map_size() const;
  void clear_ext_map();
  static const int kExtMapFieldNumber = 23;
  const ::proto::PacketHead_ExtMapEntry& ext_map(int index) const;
  ::proto::PacketHead_ExtMapEntry* mutable_ext_map(int index);
  ::proto::PacketHead_ExtMapEntry* add_ext_map();
  ::google::protobuf::RepeatedPtrField< ::proto::PacketHead_ExtMapEntry >*
      mutable_ext_map();
  const ::google::protobuf::RepeatedPtrField< ::proto::PacketHead_ExtMapEntry >&
      ext_map() const;

  // repeated .proto.PacketHead.ServiceAppIdMapEntry service_app_id_map = 33;
  int service_app_id_map_size() const;
  void clear_service_app_id_map();
  static const int kServiceAppIdMapFieldNumber = 33;
  const ::proto::PacketHead_ServiceAppIdMapEntry& service_app_id_map(int index) const;
  ::proto::PacketHead_ServiceAppIdMapEntry* mutable_service_app_id_map(int index);
  ::proto::PacketHead_ServiceAppIdMapEntry* add_service_app_id_map();
  ::google::protobuf::RepeatedPtrField< ::proto::PacketHead_ServiceAppIdMapEntry >*
      mutable_service_app_id_map();
  const ::google::protobuf::RepeatedPtrField< ::proto::PacketHead_ServiceAppIdMapEntry >&
      service_app_id_map() const;

  // bytes span_context_str = 26;
  void clear_span_context_str();
  static const int kSpanContextStrFieldNumber = 26;
  const ::std::string& span_context_str() const;
  void set_span_context_str(const ::std::string& value);
  #if LANG_CXX11
  void set_span_context_str(::std::string&& value);
  #endif
  void set_span_context_str(const char* value);
  void set_span_context_str(const void* value, size_t size);
  ::std::string* mutable_span_context_str();
  ::std::string* release_span_context_str();
  void set_allocated_span_context_str(::std::string* span_context_str);

  // uint32 packet_id = 1;
  void clear_packet_id();
  static const int kPacketIdFieldNumber = 1;
  ::google::protobuf::uint32 packet_id() const;
  void set_packet_id(::google::protobuf::uint32 value);

  // uint32 rpc_id = 2;
  void clear_rpc_id();
  static const int kRpcIdFieldNumber = 2;
  ::google::protobuf::uint32 rpc_id() const;
  void set_rpc_id(::google::protobuf::uint32 value);

  // uint32 client_sequence_id = 3;
  void clear_client_sequence_id();
  static const int kClientSequenceIdFieldNumber = 3;
  ::google::protobuf::uint32 client_sequence_id() const;
  void set_client_sequence_id(::google::protobuf::uint32 value);

  // uint32 enet_channel_id = 4;
  void clear_enet_channel_id();
  static const int kEnetChannelIdFieldNumber = 4;
  ::google::protobuf::uint32 enet_channel_id() const;
  void set_enet_channel_id(::google::protobuf::uint32 value);

  // uint64 sent_ms = 6;
  void clear_sent_ms();
  static const int kSentMsFieldNumber = 6;
  ::google::protobuf::uint64 sent_ms() const;
  void set_sent_ms(::google::protobuf::uint64 value);

  // uint32 enet_is_reliable = 5;
  void clear_enet_is_reliable();
  static const int kEnetIsReliableFieldNumber = 5;
  ::google::protobuf::uint32 enet_is_reliable() const;
  void set_enet_is_reliable(::google::protobuf::uint32 value);

  // uint32 user_id = 11;
  void clear_user_id();
  static const int kUserIdFieldNumber = 11;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // uint32 user_ip = 12;
  void clear_user_ip();
  static const int kUserIpFieldNumber = 12;
  ::google::protobuf::uint32 user_ip() const;
  void set_user_ip(::google::protobuf::uint32 value);

  // uint32 user_session_id = 13;
  void clear_user_session_id();
  static const int kUserSessionIdFieldNumber = 13;
  ::google::protobuf::uint32 user_session_id() const;
  void set_user_session_id(::google::protobuf::uint32 value);

  // uint32 home_user_id = 14;
  void clear_home_user_id();
  static const int kHomeUserIdFieldNumber = 14;
  ::google::protobuf::uint32 home_user_id() const;
  void set_home_user_id(::google::protobuf::uint32 value);

  // uint32 rpc_begin_time_ms = 22;
  void clear_rpc_begin_time_ms();
  static const int kRpcBeginTimeMsFieldNumber = 22;
  ::google::protobuf::uint32 rpc_begin_time_ms() const;
  void set_rpc_begin_time_ms(::google::protobuf::uint32 value);

  // uint64 recv_time_ms = 21;
  void clear_recv_time_ms();
  static const int kRecvTimeMsFieldNumber = 21;
  ::google::protobuf::uint64 recv_time_ms() const;
  void set_recv_time_ms(::google::protobuf::uint64 value);

  // uint32 sender_app_id = 24;
  void clear_sender_app_id();
  static const int kSenderAppIdFieldNumber = 24;
  ::google::protobuf::uint32 sender_app_id() const;
  void set_sender_app_id(::google::protobuf::uint32 value);

  // uint32 sender_load = 25;
  void clear_sender_load();
  static const int kSenderLoadFieldNumber = 25;
  ::google::protobuf::uint32 sender_load() const;
  void set_sender_load(::google::protobuf::uint32 value);

  // uint32 source_service = 31;
  void clear_source_service();
  static const int kSourceServiceFieldNumber = 31;
  ::google::protobuf::uint32 source_service() const;
  void set_source_service(::google::protobuf::uint32 value);

  // uint32 target_service = 32;
  void clear_target_service();
  static const int kTargetServiceFieldNumber = 32;
  ::google::protobuf::uint32 target_service() const;
  void set_target_service(::google::protobuf::uint32 value);

  // bool is_set_game_thread = 34;
  void clear_is_set_game_thread();
  static const int kIsSetGameThreadFieldNumber = 34;
  bool is_set_game_thread() const;
  void set_is_set_game_thread(bool value);

  // uint32 game_thread_index = 35;
  void clear_game_thread_index();
  static const int kGameThreadIndexFieldNumber = 35;
  ::google::protobuf::uint32 game_thread_index() const;
  void set_game_thread_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.PacketHead)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto::PacketHead_ExtMapEntry > ext_map_;
  ::google::protobuf::RepeatedPtrField< ::proto::PacketHead_ServiceAppIdMapEntry > service_app_id_map_;
  ::google::protobuf::internal::ArenaStringPtr span_context_str_;
  ::google::protobuf::uint32 packet_id_;
  ::google::protobuf::uint32 rpc_id_;
  ::google::protobuf::uint32 client_sequence_id_;
  ::google::protobuf::uint32 enet_channel_id_;
  ::google::protobuf::uint64 sent_ms_;
  ::google::protobuf::uint32 enet_is_reliable_;
  ::google::protobuf::uint32 user_id_;
  ::google::protobuf::uint32 user_ip_;
  ::google::protobuf::uint32 user_session_id_;
  ::google::protobuf::uint32 home_user_id_;
  ::google::protobuf::uint32 rpc_begin_time_ms_;
  ::google::protobuf::uint64 recv_time_ms_;
  ::google::protobuf::uint32 sender_app_id_;
  ::google::protobuf::uint32 sender_load_;
  ::google::protobuf::uint32 source_service_;
  ::google::protobuf::uint32 target_service_;
  bool is_set_game_thread_;
  ::google::protobuf::uint32 game_thread_index_;
  mutable int _cached_size_;
  friend struct protobuf_packet_5fhead_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DebugNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.DebugNotify) */ {
 public:
  DebugNotify();
  virtual ~DebugNotify();

  DebugNotify(const DebugNotify& from);

  inline DebugNotify& operator=(const DebugNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DebugNotify(DebugNotify&& from) noexcept
    : DebugNotify() {
    *this = ::std::move(from);
  }

  inline DebugNotify& operator=(DebugNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DebugNotify& default_instance();

  static inline const DebugNotify* internal_default_instance() {
    return reinterpret_cast<const DebugNotify*>(
               &_DebugNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(DebugNotify* other);
  friend void swap(DebugNotify& a, DebugNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DebugNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  DebugNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DebugNotify& from);
  void MergeFrom(const DebugNotify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DebugNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef DebugNotify_Enum Enum;
  static const Enum ZERO =
    DebugNotify_Enum_ZERO;
  static const Enum CMD_ID =
    DebugNotify_Enum_CMD_ID;
  static const Enum TARGET_SERVICE =
    DebugNotify_Enum_TARGET_SERVICE;
  static const Enum ENET_CHANNEL_ID =
    DebugNotify_Enum_ENET_CHANNEL_ID;
  static const Enum ENET_IS_RELIABLE =
    DebugNotify_Enum_ENET_IS_RELIABLE;
  static inline bool Enum_IsValid(int value) {
    return DebugNotify_Enum_IsValid(value);
  }
  static const Enum Enum_MIN =
    DebugNotify_Enum_Enum_MIN;
  static const Enum Enum_MAX =
    DebugNotify_Enum_Enum_MAX;
  static const int Enum_ARRAYSIZE =
    DebugNotify_Enum_Enum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Enum_descriptor() {
    return DebugNotify_Enum_descriptor();
  }
  static inline const ::std::string& Enum_Name(Enum value) {
    return DebugNotify_Enum_Name(value);
  }
  static inline bool Enum_Parse(const ::std::string& name,
      Enum* value) {
    return DebugNotify_Enum_Parse(name, value);
  }

  typedef DebugNotify_Retcode Retcode;
  static const Retcode SUCC =
    DebugNotify_Retcode_SUCC;
  static const Retcode FAIL =
    DebugNotify_Retcode_FAIL;
  static inline bool Retcode_IsValid(int value) {
    return DebugNotify_Retcode_IsValid(value);
  }
  static const Retcode Retcode_MIN =
    DebugNotify_Retcode_Retcode_MIN;
  static const Retcode Retcode_MAX =
    DebugNotify_Retcode_Retcode_MAX;
  static const int Retcode_ARRAYSIZE =
    DebugNotify_Retcode_Retcode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Retcode_descriptor() {
    return DebugNotify_Retcode_descriptor();
  }
  static inline const ::std::string& Retcode_Name(Retcode value) {
    return DebugNotify_Retcode_Name(value);
  }
  static inline bool Retcode_Parse(const ::std::string& name,
      Retcode* value) {
    return DebugNotify_Retcode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // .proto.DebugNotify.Retcode retcode = 3;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 3;
  ::proto::DebugNotify_Retcode retcode() const;
  void set_retcode(::proto::DebugNotify_Retcode value);

  // @@protoc_insertion_point(class_scope:proto.DebugNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 id_;
  int retcode_;
  mutable int _cached_size_;
  friend struct protobuf_packet_5fhead_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::proto::DebugNotify_Enum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::DebugNotify_Enum>() {
  return ::proto::DebugNotify_Enum_descriptor();
}
template <> struct is_proto_enum< ::proto::DebugNotify_Retcode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::DebugNotify_Retcode>() {
  return ::proto::DebugNotify_Retcode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_packet_5fhead_2eproto__INCLUDED
