// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: define.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "define.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
class ParamListDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ParamList>
     _instance;
} _ParamList_default_instance_;
class PropValueDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PropValue>
     _instance;
  ::google::protobuf::int64 ival_;
  float fval_;
} _PropValue_default_instance_;
class Uint32PairDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Uint32Pair>
     _instance;
} _Uint32Pair_default_instance_;
class RegionSimpleInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RegionSimpleInfo>
     _instance;
} _RegionSimpleInfo_default_instance_;
class QueryRegionListHttpRspDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<QueryRegionListHttpRsp>
     _instance;
} _QueryRegionListHttpRsp_default_instance_;
class ForceUpdateInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ForceUpdateInfo>
     _instance;
} _ForceUpdateInfo_default_instance_;
class StopServerInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<StopServerInfo>
     _instance;
} _StopServerInfo_default_instance_;
class ResVersionConfigDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ResVersionConfig>
     _instance;
} _ResVersionConfig_default_instance_;
class RegionInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RegionInfo>
     _instance;
} _RegionInfo_default_instance_;
class QueryCurrRegionHttpRspDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<QueryCurrRegionHttpRsp>
     _instance;
  const ::proto::ForceUpdateInfo* force_udpate_;
  const ::proto::StopServerInfo* stop_server_;
} _QueryCurrRegionHttpRsp_default_instance_;
class PlayerUidExtInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PlayerUidExtInfo>
     _instance;
} _PlayerUidExtInfo_default_instance_;
class ReliquaryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Reliquary>
     _instance;
} _Reliquary_default_instance_;
class Weapon_AffixMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Weapon::Weapon_AffixMapEntry>
     _instance;
} _Weapon_AffixMapEntry_default_instance_;
class WeaponDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Weapon>
     _instance;
} _Weapon_default_instance_;
class MaterialDeleteInfo_CountDownDelete_DeleteTimeNumMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MaterialDeleteInfo_CountDownDelete::MaterialDeleteInfo_CountDownDelete_DeleteTimeNumMapEntry>
     _instance;
} _MaterialDeleteInfo_CountDownDelete_DeleteTimeNumMapEntry_default_instance_;
class MaterialDeleteInfo_CountDownDeleteDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MaterialDeleteInfo_CountDownDelete>
     _instance;
} _MaterialDeleteInfo_CountDownDelete_default_instance_;
class MaterialDeleteInfo_DateTimeDeleteDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MaterialDeleteInfo_DateTimeDelete>
     _instance;
} _MaterialDeleteInfo_DateTimeDelete_default_instance_;
class MaterialDeleteInfo_DelayWeekCountDownDelete_DeleteTimeNumMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MaterialDeleteInfo_DelayWeekCountDownDelete::MaterialDeleteInfo_DelayWeekCountDownDelete_DeleteTimeNumMapEntry>
     _instance;
} _MaterialDeleteInfo_DelayWeekCountDownDelete_DeleteTimeNumMapEntry_default_instance_;
class MaterialDeleteInfo_DelayWeekCountDownDeleteDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MaterialDeleteInfo_DelayWeekCountDownDelete>
     _instance;
} _MaterialDeleteInfo_DelayWeekCountDownDelete_default_instance_;
class MaterialDeleteInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MaterialDeleteInfo>
     _instance;
  const ::proto::MaterialDeleteInfo_CountDownDelete* count_down_delete_;
  const ::proto::MaterialDeleteInfo_DateTimeDelete* date_delete_;
  const ::proto::MaterialDeleteInfo_DelayWeekCountDownDelete* delay_week_count_down_delete_;
} _MaterialDeleteInfo_default_instance_;
class MaterialDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Material>
     _instance;
} _Material_default_instance_;
class EquipDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Equip>
     _instance;
  const ::proto::Reliquary* reliquary_;
  const ::proto::Weapon* weapon_;
} _Equip_default_instance_;
class FurnitureDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Furniture>
     _instance;
} _Furniture_default_instance_;
class ItemDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Item>
     _instance;
  const ::proto::Material* material_;
  const ::proto::Equip* equip_;
  const ::proto::Furniture* furniture_;
} _Item_default_instance_;
class ItemParamDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ItemParam>
     _instance;
} _ItemParam_default_instance_;
class EquipParamDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EquipParam>
     _instance;
} _EquipParam_default_instance_;
class EquipParamListDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EquipParamList>
     _instance;
} _EquipParamList_default_instance_;
class RewardDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Reward>
     _instance;
} _Reward_default_instance_;
class AbilityStringDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityString>
     _instance;
  ::google::protobuf::internal::ArenaStringPtr str_;
  ::google::protobuf::uint32 hash_;
} _AbilityString_default_instance_;
class AbilityFloatValueDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityFloatValue>
     _instance;
} _AbilityFloatValue_default_instance_;
class AbilityScalarValueEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityScalarValueEntry>
     _instance;
  float float_value_;
  ::google::protobuf::internal::ArenaStringPtr string_value_;
  ::google::protobuf::int32 int_value_;
  ::google::protobuf::uint32 uint_value_;
} _AbilityScalarValueEntry_default_instance_;
class AbilityAppliedAbilityDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityAppliedAbility>
     _instance;
} _AbilityAppliedAbility_default_instance_;
class AbilityAttachedModifierDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityAttachedModifier>
     _instance;
} _AbilityAttachedModifier_default_instance_;
class ModifierDurabilityDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ModifierDurability>
     _instance;
} _ModifierDurability_default_instance_;
class AbilityAppliedModifierDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityAppliedModifier>
     _instance;
} _AbilityAppliedModifier_default_instance_;
class MassivePropParamDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MassivePropParam>
     _instance;
} _MassivePropParam_default_instance_;
class MassivePropSyncInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MassivePropSyncInfo>
     _instance;
} _MassivePropSyncInfo_default_instance_;
class BreakoutVector2DefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutVector2>
     _instance;
} _BreakoutVector2_default_instance_;
class BreakoutBrickInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutBrickInfo>
     _instance;
} _BreakoutBrickInfo_default_instance_;
class BreakoutPhysicalObjectModifierDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutPhysicalObjectModifier>
     _instance;
} _BreakoutPhysicalObjectModifier_default_instance_;
class BreakoutPhysicalObjectDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutPhysicalObject>
     _instance;
} _BreakoutPhysicalObject_default_instance_;
class BreakoutSpawnPointDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutSpawnPoint>
     _instance;
} _BreakoutSpawnPoint_default_instance_;
class BreakoutElementReactionCounterDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutElementReactionCounter>
     _instance;
} _BreakoutElementReactionCounter_default_instance_;
class BreakoutSyncConnectUidInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutSyncConnectUidInfo>
     _instance;
} _BreakoutSyncConnectUidInfo_default_instance_;
class BreakoutSnapShotDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutSnapShot>
     _instance;
} _BreakoutSnapShot_default_instance_;
class BreakoutActionDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BreakoutAction>
     _instance;
} _BreakoutAction_default_instance_;
class AbilityMixinRecoverInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityMixinRecoverInfo>
     _instance;
  ::google::protobuf::uint32 instanced_ability_id_;
  ::google::protobuf::uint32 instanced_modifier_id_;
} _AbilityMixinRecoverInfo_default_instance_;
class AbilitySyncStateInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilitySyncStateInfo>
     _instance;
} _AbilitySyncStateInfo_default_instance_;
class AbilityEmbryoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityEmbryo>
     _instance;
} _AbilityEmbryo_default_instance_;
class AbilityControlBlockDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityControlBlock>
     _instance;
} _AbilityControlBlock_default_instance_;
class VectorDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Vector>
     _instance;
} _Vector_default_instance_;
class VectorPlaneDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<VectorPlane>
     _instance;
} _VectorPlane_default_instance_;
class Vector3IntDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Vector3Int>
     _instance;
} _Vector3Int_default_instance_;
class EntityMoveInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EntityMoveInfo>
     _instance;
} _EntityMoveInfo_default_instance_;
class MotionInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MotionInfo>
     _instance;
} _MotionInfo_default_instance_;
class PlaceInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PlaceInfo>
     _instance;
} _PlaceInfo_default_instance_;
class SceneWeaponInfo_AffixMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneWeaponInfo::SceneWeaponInfo_AffixMapEntry>
     _instance;
} _SceneWeaponInfo_AffixMapEntry_default_instance_;
class SceneWeaponInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneWeaponInfo>
     _instance;
} _SceneWeaponInfo_default_instance_;
class SceneReliquaryInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneReliquaryInfo>
     _instance;
} _SceneReliquaryInfo_default_instance_;
class ServerBuffDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ServerBuff>
     _instance;
} _ServerBuff_default_instance_;
class CurVehicleInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CurVehicleInfo>
     _instance;
} _CurVehicleInfo_default_instance_;
class AvatarExcelInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarExcelInfo>
     _instance;
} _AvatarExcelInfo_default_instance_;
class SceneAvatarInfo_SkillLevelMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneAvatarInfo::SceneAvatarInfo_SkillLevelMapEntry>
     _instance;
} _SceneAvatarInfo_SkillLevelMapEntry_default_instance_;
class SceneAvatarInfo_ProudSkillExtraLevelMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneAvatarInfo::SceneAvatarInfo_ProudSkillExtraLevelMapEntry>
     _instance;
} _SceneAvatarInfo_ProudSkillExtraLevelMapEntry_default_instance_;
class SceneAvatarInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneAvatarInfo>
     _instance;
} _SceneAvatarInfo_default_instance_;
class SceneFishInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneFishInfo>
     _instance;
} _SceneFishInfo_default_instance_;
class FishtankFishInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<FishtankFishInfo>
     _instance;
} _FishtankFishInfo_default_instance_;
class SceneMonsterInfo_SummonTagMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneMonsterInfo::SceneMonsterInfo_SummonTagMapEntry>
     _instance;
} _SceneMonsterInfo_SummonTagMapEntry_default_instance_;
class SceneMonsterInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneMonsterInfo>
     _instance;
  const ::proto::SceneFishInfo* fish_info_;
  const ::proto::FishtankFishInfo* fishtank_fish_info_;
} _SceneMonsterInfo_default_instance_;
class SceneNpcInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneNpcInfo>
     _instance;
} _SceneNpcInfo_default_instance_;
class WorktopInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<WorktopInfo>
     _instance;
} _WorktopInfo_default_instance_;
class MathQuaternionDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MathQuaternion>
     _instance;
} _MathQuaternion_default_instance_;
class PlatformInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PlatformInfo>
     _instance;
} _PlatformInfo_default_instance_;
class RoutePointDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RoutePoint>
     _instance;
  float velocity_;
  float time_;
  const ::proto::Vector* rotation_;
  const ::proto::MathQuaternion* rotation_speed_;
  const ::proto::MathQuaternion* axis_speed_;
} _RoutePoint_default_instance_;
class RouteDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Route>
     _instance;
} _Route_default_instance_;
class MonsterRouteDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MonsterRoute>
     _instance;
} _MonsterRoute_default_instance_;
class WeatherInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<WeatherInfo>
     _instance;
} _WeatherInfo_default_instance_;
class ClientGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ClientGadgetInfo>
     _instance;
} _ClientGadgetInfo_default_instance_;
class AbilityGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AbilityGadgetInfo>
     _instance;
} _AbilityGadgetInfo_default_instance_;
class GatherGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GatherGadgetInfo>
     _instance;
} _GatherGadgetInfo_default_instance_;
class StatueGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<StatueGadgetInfo>
     _instance;
} _StatueGadgetInfo_default_instance_;
class WeeklyBossResinDiscountInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<WeeklyBossResinDiscountInfo>
     _instance;
} _WeeklyBossResinDiscountInfo_default_instance_;
class BossChestInfo_UidDiscountMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BossChestInfo::BossChestInfo_UidDiscountMapEntry>
     _instance;
} _BossChestInfo_UidDiscountMapEntry_default_instance_;
class BossChestInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BossChestInfo>
     _instance;
} _BossChestInfo_default_instance_;
class BlossomChestInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BlossomChestInfo>
     _instance;
} _BlossomChestInfo_default_instance_;
class GadgetCrucibleInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GadgetCrucibleInfo>
     _instance;
} _GadgetCrucibleInfo_default_instance_;
class GadgetPlayInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GadgetPlayInfo>
     _instance;
  const ::proto::GadgetCrucibleInfo* crucible_info_;
} _GadgetPlayInfo_default_instance_;
class MpPlayRewardInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MpPlayRewardInfo>
     _instance;
} _MpPlayRewardInfo_default_instance_;
class GadgetGeneralRewardInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GadgetGeneralRewardInfo>
     _instance;
} _GadgetGeneralRewardInfo_default_instance_;
class OfferingInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<OfferingInfo>
     _instance;
} _OfferingInfo_default_instance_;
class BuildingInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BuildingInfo>
     _instance;
} _BuildingInfo_default_instance_;
class FoundationInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<FoundationInfo>
     _instance;
} _FoundationInfo_default_instance_;
class VehicleMemberDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<VehicleMember>
     _instance;
} _VehicleMember_default_instance_;
class VehicleInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<VehicleInfo>
     _instance;
} _VehicleInfo_default_instance_;
class EchoShellInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EchoShellInfo>
     _instance;
} _EchoShellInfo_default_instance_;
class ScreenInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ScreenInfo>
     _instance;
} _ScreenInfo_default_instance_;
class FishPoolInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<FishPoolInfo>
     _instance;
} _FishPoolInfo_default_instance_;
class CustomCommonNodeInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomCommonNodeInfo>
     _instance;
} _CustomCommonNodeInfo_default_instance_;
class CustomGadgetTreeInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomGadgetTreeInfo>
     _instance;
} _CustomGadgetTreeInfo_default_instance_;
class RoguelikeGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RoguelikeGadgetInfo>
     _instance;
} _RoguelikeGadgetInfo_default_instance_;
class NightCrowGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<NightCrowGadgetInfo>
     _instance;
} _NightCrowGadgetInfo_default_instance_;
class DeshretObeliskGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<DeshretObeliskGadgetInfo>
     _instance;
} _DeshretObeliskGadgetInfo_default_instance_;
class CoinCollectOperatorInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CoinCollectOperatorInfo>
     _instance;
} _CoinCollectOperatorInfo_default_instance_;
class SceneGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneGadgetInfo>
     _instance;
  const ::proto::Item* trifle_item_;
  const ::proto::GatherGadgetInfo* gather_gadget_;
  const ::proto::WorktopInfo* worktop_;
  const ::proto::ClientGadgetInfo* client_gadget_;
  const ::proto::WeatherInfo* weather_;
  const ::proto::AbilityGadgetInfo* ability_gadget_;
  const ::proto::StatueGadgetInfo* statue_gadget_;
  const ::proto::BossChestInfo* boss_chest_;
  const ::proto::BlossomChestInfo* blossom_chest_;
  const ::proto::MpPlayRewardInfo* mp_play_reward_;
  const ::proto::GadgetGeneralRewardInfo* general_reward_;
  const ::proto::OfferingInfo* offering_info_;
  const ::proto::FoundationInfo* foundation_info_;
  const ::proto::VehicleInfo* vehicle_info_;
  const ::proto::EchoShellInfo* shell_info_;
  const ::proto::ScreenInfo* screen_info_;
  const ::proto::FishPoolInfo* fish_pool_info_;
  const ::proto::CustomGadgetTreeInfo* custom_gadget_tree_info_;
  const ::proto::RoguelikeGadgetInfo* roguelike_gadget_info_;
  const ::proto::NightCrowGadgetInfo* night_crow_gadget_info_;
  const ::proto::DeshretObeliskGadgetInfo* deshret_obelisk_gadget_info_;
  const ::proto::CoinCollectOperatorInfo* coin_collect_operator_info_;
} _SceneGadgetInfo_default_instance_;
class AnimatorParameterValueInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AnimatorParameterValueInfo>
     _instance;
  ::google::protobuf::int32 int_val_;
  float float_val_;
  bool bool_val_;
} _AnimatorParameterValueInfo_default_instance_;
class ServantInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ServantInfo>
     _instance;
} _ServantInfo_default_instance_;
class SceneEntityAiInfo_SkillCdMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneEntityAiInfo::SceneEntityAiInfo_SkillCdMapEntry>
     _instance;
} _SceneEntityAiInfo_SkillCdMapEntry_default_instance_;
class SceneEntityAiInfo_AiThreatMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneEntityAiInfo::SceneEntityAiInfo_AiThreatMapEntry>
     _instance;
} _SceneEntityAiInfo_AiThreatMapEntry_default_instance_;
class SceneEntityAiInfo_SkillGroupCdMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneEntityAiInfo::SceneEntityAiInfo_SkillGroupCdMapEntry>
     _instance;
} _SceneEntityAiInfo_SkillGroupCdMapEntry_default_instance_;
class SceneEntityAiInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneEntityAiInfo>
     _instance;
} _SceneEntityAiInfo_default_instance_;
class EntityRendererChangedInfo_ChangedRenderersEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EntityRendererChangedInfo::EntityRendererChangedInfo_ChangedRenderersEntry>
     _instance;
} _EntityRendererChangedInfo_ChangedRenderersEntry_default_instance_;
class EntityRendererChangedInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EntityRendererChangedInfo>
     _instance;
} _EntityRendererChangedInfo_default_instance_;
class PropPairDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PropPair>
     _instance;
} _PropPair_default_instance_;
class FightPropPairDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<FightPropPair>
     _instance;
} _FightPropPair_default_instance_;
class AnimatorParameterValueInfoPairDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AnimatorParameterValueInfoPair>
     _instance;
} _AnimatorParameterValueInfoPair_default_instance_;
class EntityEnvironmentInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EntityEnvironmentInfo>
     _instance;
} _EntityEnvironmentInfo_default_instance_;
class EntityClientExtraInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EntityClientExtraInfo>
     _instance;
} _EntityClientExtraInfo_default_instance_;
class EntityAuthorityInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EntityAuthorityInfo>
     _instance;
} _EntityAuthorityInfo_default_instance_;
class SceneEntityInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SceneEntityInfo>
     _instance;
  const ::proto::SceneAvatarInfo* avatar_;
  const ::proto::SceneMonsterInfo* monster_;
  const ::proto::SceneNpcInfo* npc_;
  const ::proto::SceneGadgetInfo* gadget_;
} _SceneEntityInfo_default_instance_;
class CreateGadgetInfo_ChestDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CreateGadgetInfo_Chest>
     _instance;
} _CreateGadgetInfo_Chest_default_instance_;
class CreateGadgetInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CreateGadgetInfo>
     _instance;
} _CreateGadgetInfo_default_instance_;
class CreateEntityInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CreateEntityInfo>
     _instance;
  ::google::protobuf::uint32 monster_id_;
  ::google::protobuf::uint32 npc_id_;
  ::google::protobuf::uint32 gadget_id_;
  ::google::protobuf::uint32 item_id_;
  const ::proto::CreateGadgetInfo* gadget_;
} _CreateEntityInfo_default_instance_;
class TrialAvatarGrantRecordDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<TrialAvatarGrantRecord>
     _instance;
} _TrialAvatarGrantRecord_default_instance_;
class TrialAvatarInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<TrialAvatarInfo>
     _instance;
} _TrialAvatarInfo_default_instance_;
class AvatarSkillInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarSkillInfo>
     _instance;
} _AvatarSkillInfo_default_instance_;
class FetterDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<FetterData>
     _instance;
} _FetterData_default_instance_;
class AvatarFetterInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarFetterInfo>
     _instance;
} _AvatarFetterInfo_default_instance_;
class AvatarExpeditionInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarExpeditionInfo>
     _instance;
} _AvatarExpeditionInfo_default_instance_;
class AvatarEquipAffixInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarEquipAffixInfo>
     _instance;
} _AvatarEquipAffixInfo_default_instance_;
class AvatarInfo_PropMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarInfo::AvatarInfo_PropMapEntry>
     _instance;
} _AvatarInfo_PropMapEntry_default_instance_;
class AvatarInfo_FightPropMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarInfo::AvatarInfo_FightPropMapEntry>
     _instance;
} _AvatarInfo_FightPropMapEntry_default_instance_;
class AvatarInfo_SkillMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarInfo::AvatarInfo_SkillMapEntry>
     _instance;
} _AvatarInfo_SkillMapEntry_default_instance_;
class AvatarInfo_SkillLevelMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarInfo::AvatarInfo_SkillLevelMapEntry>
     _instance;
} _AvatarInfo_SkillLevelMapEntry_default_instance_;
class AvatarInfo_ProudSkillExtraLevelMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarInfo::AvatarInfo_ProudSkillExtraLevelMapEntry>
     _instance;
} _AvatarInfo_ProudSkillExtraLevelMapEntry_default_instance_;
class AvatarInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarInfo>
     _instance;
} _AvatarInfo_default_instance_;
class ShowEquipDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShowEquip>
     _instance;
  const ::proto::Reliquary* reliquary_;
  const ::proto::Weapon* weapon_;
} _ShowEquip_default_instance_;
class ShowAvatarInfo_PropMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShowAvatarInfo::ShowAvatarInfo_PropMapEntry>
     _instance;
} _ShowAvatarInfo_PropMapEntry_default_instance_;
class ShowAvatarInfo_FightPropMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShowAvatarInfo::ShowAvatarInfo_FightPropMapEntry>
     _instance;
} _ShowAvatarInfo_FightPropMapEntry_default_instance_;
class ShowAvatarInfo_SkillLevelMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShowAvatarInfo::ShowAvatarInfo_SkillLevelMapEntry>
     _instance;
} _ShowAvatarInfo_SkillLevelMapEntry_default_instance_;
class ShowAvatarInfo_ProudSkillExtraLevelMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShowAvatarInfo::ShowAvatarInfo_ProudSkillExtraLevelMapEntry>
     _instance;
} _ShowAvatarInfo_ProudSkillExtraLevelMapEntry_default_instance_;
class ShowAvatarInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShowAvatarInfo>
     _instance;
} _ShowAvatarInfo_default_instance_;
class Quest_LackedNpcMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Quest::Quest_LackedNpcMapEntry>
     _instance;
} _Quest_LackedNpcMapEntry_default_instance_;
class Quest_LackedPlaceMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Quest::Quest_LackedPlaceMapEntry>
     _instance;
} _Quest_LackedPlaceMapEntry_default_instance_;
class QuestDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Quest>
     _instance;
} _Quest_default_instance_;
class NpcPositionInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<NpcPositionInfo>
     _instance;
} _NpcPositionInfo_default_instance_;
class MailTextContentDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MailTextContent>
     _instance;
} _MailTextContent_default_instance_;
class MailItemDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MailItem>
     _instance;
} _MailItem_default_instance_;
class MailDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MailData>
     _instance;
} _MailData_default_instance_;
class OnlinePlayerInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<OnlinePlayerInfo>
     _instance;
} _OnlinePlayerInfo_default_instance_;
class BirthdayDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Birthday>
     _instance;
} _Birthday_default_instance_;
class MapMarkPointDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MapMarkPoint>
     _instance;
} _MapMarkPoint_default_instance_;
class MassiveWaterInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MassiveWaterInfo>
     _instance;
} _MassiveWaterInfo_default_instance_;
class MassiveGrassInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MassiveGrassInfo>
     _instance;
} _MassiveGrassInfo_default_instance_;
class MassiveBoxInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MassiveBoxInfo>
     _instance;
} _MassiveBoxInfo_default_instance_;
class ClientMassiveEntityDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ClientMassiveEntity>
     _instance;
  const ::proto::MassiveWaterInfo* water_info_;
  const ::proto::MassiveGrassInfo* grass_info_;
  const ::proto::MassiveBoxInfo* box_info_;
} _ClientMassiveEntity_default_instance_;
class ShapeSphereDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShapeSphere>
     _instance;
} _ShapeSphere_default_instance_;
class ShapeBoxDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShapeBox>
     _instance;
} _ShapeBox_default_instance_;
class ServerMassiveEntityDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ServerMassiveEntity>
     _instance;
  const ::proto::MassiveWaterInfo* water_info_;
  const ::proto::MassiveGrassInfo* grass_info_;
  const ::proto::MassiveBoxInfo* box_info_;
} _ServerMassiveEntity_default_instance_;
class MassiveEntityStateDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MassiveEntityState>
     _instance;
} _MassiveEntityState_default_instance_;
class EntityClientDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<EntityClientData>
     _instance;
} _EntityClientData_default_instance_;
class BlockInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<BlockInfo>
     _instance;
} _BlockInfo_default_instance_;
class ShopMcoinProductDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShopMcoinProduct>
     _instance;
} _ShopMcoinProduct_default_instance_;
class ShopCardProduct_ResinCardDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShopCardProduct_ResinCard>
     _instance;
} _ShopCardProduct_ResinCard_default_instance_;
class ShopCardProductDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShopCardProduct>
     _instance;
  const ::proto::ShopCardProduct_ResinCard* resin_card_;
} _ShopCardProduct_default_instance_;
class PlayProductDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PlayProduct>
     _instance;
} _PlayProduct_default_instance_;
class ShopConcertProductDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ShopConcertProduct>
     _instance;
} _ShopConcertProduct_default_instance_;
class HashedStringDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HashedString>
     _instance;
} _HashedString_default_instance_;
class PlayTeamEntityInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PlayTeamEntityInfo>
     _instance;
} _PlayTeamEntityInfo_default_instance_;
class FeatureBlockInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<FeatureBlockInfo>
     _instance;
} _FeatureBlockInfo_default_instance_;
class MapMarkTipsInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MapMarkTipsInfo>
     _instance;
} _MapMarkTipsInfo_default_instance_;
class ExhibitionDisplayInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ExhibitionDisplayInfo>
     _instance;
} _ExhibitionDisplayInfo_default_instance_;
class ProfilePictureDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ProfilePicture>
     _instance;
} _ProfilePicture_default_instance_;
class RedPointDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<RedPointData>
     _instance;
} _RedPointData_default_instance_;
class HomeMarkPointNPCDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HomeMarkPointNPCData>
     _instance;
} _HomeMarkPointNPCData_default_instance_;
class HomeMarkPointSuiteDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HomeMarkPointSuiteData>
     _instance;
} _HomeMarkPointSuiteData_default_instance_;
class HomeMarkPointFurnitureDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HomeMarkPointFurnitureData>
     _instance;
  const ::proto::HomeMarkPointNPCData* npc_data_;
  const ::proto::HomeMarkPointSuiteData* suite_data_;
} _HomeMarkPointFurnitureData_default_instance_;
class MapAreaInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MapAreaInfo>
     _instance;
} _MapAreaInfo_default_instance_;
class HomeFurnitureArrangementMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HomeFurnitureArrangementMuipData>
     _instance;
} _HomeFurnitureArrangementMuipData_default_instance_;
class HomeBlockArrangementMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HomeBlockArrangementMuipData>
     _instance;
} _HomeBlockArrangementMuipData_default_instance_;
class HomeSceneArrangementMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HomeSceneArrangementMuipData>
     _instance;
} _HomeSceneArrangementMuipData_default_instance_;
class CustomDungeonBattleRecordMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomDungeonBattleRecordMuipData>
     _instance;
} _CustomDungeonBattleRecordMuipData_default_instance_;
class PlayerCustomDungeonMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<PlayerCustomDungeonMuipData>
     _instance;
} _PlayerCustomDungeonMuipData_default_instance_;
class CustomDungeonSettingMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomDungeonSettingMuipData>
     _instance;
} _CustomDungeonSettingMuipData_default_instance_;
class CustomDungeonAbstractMuipData_BrickStatisticsMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomDungeonAbstractMuipData::CustomDungeonAbstractMuipData_BrickStatisticsMapEntry>
     _instance;
} _CustomDungeonAbstractMuipData_BrickStatisticsMapEntry_default_instance_;
class CustomDungeonAbstractMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomDungeonAbstractMuipData>
     _instance;
} _CustomDungeonAbstractMuipData_default_instance_;
class CustomDungeonSocialMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomDungeonSocialMuipData>
     _instance;
} _CustomDungeonSocialMuipData_default_instance_;
class CustomDungeonBriefMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomDungeonBriefMuipData>
     _instance;
} _CustomDungeonBriefMuipData_default_instance_;
class CustomDungeonBatchBriefMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CustomDungeonBatchBriefMuipData>
     _instance;
} _CustomDungeonBatchBriefMuipData_default_instance_;
class HomeBlueprintBriefMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HomeBlueprintBriefMuipData>
     _instance;
} _HomeBlueprintBriefMuipData_default_instance_;
class HomeBlueprintBatchBriefMuipDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<HomeBlueprintBatchBriefMuipData>
     _instance;
} _HomeBlueprintBatchBriefMuipData_default_instance_;
class ContentAuditInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ContentAuditInfo>
     _instance;
} _ContentAuditInfo_default_instance_;
class ContentAuditDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ContentAuditData>
     _instance;
} _ContentAuditData_default_instance_;
class ContentAuditFieldDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ContentAuditField>
     _instance;
} _ContentAuditField_default_instance_;
class ContentAuditAuxiliaryFieldDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ContentAuditAuxiliaryField>
     _instance;
} _ContentAuditAuxiliaryField_default_instance_;
class NicknameSignatureAuditDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<NicknameSignatureAuditData>
     _instance;
} _NicknameSignatureAuditData_default_instance_;
class AvatarRenameAuditContentDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarRenameAuditContent>
     _instance;
} _AvatarRenameAuditContent_default_instance_;
class AvatarRenameContentAuditFieldDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarRenameContentAuditField>
     _instance;
} _AvatarRenameContentAuditField_default_instance_;
class AvatarRenameAuditDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AvatarRenameAuditData>
     _instance;
} _AvatarRenameAuditData_default_instance_;
class ActivityDungeonAvatarDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<ActivityDungeonAvatar>
     _instance;
} _ActivityDungeonAvatar_default_instance_;
class GCGChallengeDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GCGChallengeData>
     _instance;
} _GCGChallengeData_default_instance_;
class GCGDuelExtra_CardFaceMapEntryDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GCGDuelExtra::GCGDuelExtra_CardFaceMapEntry>
     _instance;
} _GCGDuelExtra_CardFaceMapEntry_default_instance_;
class GCGDuelExtraDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GCGDuelExtra>
     _instance;
} _GCGDuelExtra_default_instance_;
class QueryIpRegionDataDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<QueryIpRegionData>
     _instance;
} _QueryIpRegionData_default_instance_;


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)
