// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: editor.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "editor.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
class MapInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MapInfo>
     _instance;
} _MapInfo_default_instance_;
class CellInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CellInfo>
     _instance;
} _CellInfo_default_instance_;


}  // namespace proto

// @@protoc_insertion_point(global_scope)
